name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # or your source branch name
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Needed to push to the deployment branch
    steps:
      # Step 1: Check out the repository (including submodules for themes)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      # Step 2: Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # or specify a version like "0.121.0"
          extended: true          # if your theme uses Sass/SCSS

      # Step 3: Build the site
      - name: Build
        run: hugo --minify

      # Step 4: Deploy the generated site to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          